### ISSUE TITLE
Comparing int with unsigned int. GCC warning.

### ISSUE THREAD

**Issue by ViralTaco** [douglascrockford/JSON-c#3]
Hi.
I just wanted to mention this: 
`
JSON_checker.c:289:19: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
    if (jc->valid != GOOD) {
        ~~~~~~~~~ ^  ~~~~
JSON_checker.c:415:19: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
    if (jc->valid != GOOD) {
        ~~~~~~~~~ ^  ~~~~
`
It's not a big deal really, well… 
I'm unsure of what you're trying to accomplish. 
0xBABAB00E = 3132796942
Which is too big for an int so it overflows to -1162170354… Which makes sense. 

Anyway all of that to say you could have used `#define GOOD (int) 0xBABAB00E`

**Comment by douglascrockford** [comment]
It is hex. The warning is in error. File a bug with GCC.

**Comment by ViralTaco** [comment]
I dissagree. There is no bug to file with GCC because it's warning you that 3132796942 and -1162170354 are different. 

I'm not a mathematician but feel free to correct me on that. 

Therefore, even though it should work. It's not valid C. It's not defined behaviour. (As far as I know)
ints are **NOT** required to be 32bit.

**Comment by douglascrockford** [comment]
The value being compared to is a bit pattern, not a number. The code is correct.

**Comment by AnthonyCapobianco** [comment]
https://wiki.sei.cmu.edu/confluence/display/c/INT31-C.+Ensure+that+integer+conversions+do+not+result+in+lost+or+misinterpreted+data

**Comment by douglascrockford** [comment]
Your citation is irrelevant. The value in this cases is not used for computation. It is used to assure that a data structure has been initialized. It does that correctly.

**Comment by AnthonyCapobianco** [comment]
`#define GOOD 0xBABAB00E`
In the typedef struct: `int valid;`
in the new_JSON_checker(int depth) function: `jc->valid = GOOD;`

>  It does that correctly.

I don't know in which standard. 

`int main(int argc, char* argv[])` instead of `int main(void)` by the way.

But it could be worse. Could be `unsigned int main()` (No, it couldn't but I think you get my point.) or `void main()`.

I appreciate that you took the time to consider the potential issue I filled. 
Thank you for your time. 

This being my last answer to this thread I invite anyone whom decides to use this library (and not another open-source alternative) to make sure to check for compiler warnings and if you care to adjust the code so that it _works on your implementation_. (Especially if you are still running a 32bit machine)

Here is an example of the kind of behaviour you can expect: [Why Not Mix Signed and Unsigned Values in C/C++?](https://blog.regehr.org/archives/268)

Also while you're at it you can check this: [Do I cast the result of malloc?](https://stackoverflow.com/a/605858/9282847)

Casting malloc is valid C. I wouldn't do it (anymore).
Especially if I don't check for a potential malloc failure. 
But that's just me.

Regards.

**Comment by rahowar1488** [comment]
• 
•

**Comment by rahowar1488** [comment]
- 
##
